### ISSUE TITLE
Fails to build with Coq 8.8.0

### ISSUE THREAD

**Issue by Armael** [pedagand/coq-label#7]
coq-labels seems broken when using Coq 8.8.0:

```
$ make                                                                                                                                                        coq_makefile -f _CoqProject -o Makefile.coq
make -f Makefile.coq
make[1]: Entering directory '/home/armael/Src/coq-label'
COQDEP VFILES
*** Warning: label_plugin.ml4 already found in src (discarding ./src/label_plugin.ml4)
CAMLDEP -pp src/label_plugin.ml4
CAMLOPT -pp -c  src/label_plugin.ml4
File "src/label_plugin.ml4", line 25, characters 6-38:
Error: Unbound value Constr_matching.is_matching_conv

```

**Comment by fpottier** [comment]
Is there any chance that this package will be updated for Coq >= 8.8?
